[workspace]

members = [
    "graph",
    "cfg-ir",
    "ast-ir",
    "lua51-lifter",
    "cfg-to-ast",
    "luau-lifter"
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = true