[workspace]

members = [
    "graph",
    "cfg",
    "ast",
    "lua51-lifter",
    "lua51-deserializer",
    #"cfg-to-ast",
    #"luau-lifter",
    #"cfg-to-ast-new"
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = true