name = "medal-dec"
type = "rust"
workers_dev = true
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.3.0"

[[d1_databases]]
binding = "medal"
database_name = "medal"
database_id = "3fa56362-0ef7-47ed-8136-36a5c0bfd543"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration