[package]
name = "ast"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
derive_more = "0.99.17"
enum-as-inner = "0.5.1"
itertools = "0.10.5"
enum_dispatch = "0.3.8"
by_address = "2.1.0"
rustc-hash = "1.1.0"

[features]
no_local_debug = []