[package]
name = "luau-worker"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
worker = "0.0.23"
luau-lifter = { path = "../luau-lifter" }

[lib]
crate-type = ["cdylib"]
